# Generated by Django 3.1.4 on 2023-08-24 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='reply',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='liked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
